Navigation And Recycler View
SofranSebastian/TaskKeeper pull request #1
Opened 2021-05-25 09:14 UTC by SofranSebastian

2021-05-25 14:32 UTC, pclRobert approved these changes
Tips

2021-05-25 14:32 UTC, pclRobert commented on app/src/main/java/com/example/taskkeeper/taskdetail/TaskDetailFragment.kt
> +        val binding : FragmentTaskDetailBinding = DataBindingUtil.inflate( inflater, R.layout.fragment_task_detail, container, false)
`binding` ar putea fi variabila globala in clasa asta, pentru ca o sa mai ai nevoie de ea mai incolo

2021-05-25 14:32 UTC, pclRobert commented on app/src/main/java/com/example/taskkeeper/taskdetail/TaskDetailFragment.kt
> +    override fun onCreateView( inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle? ) : View? {
In metoda asta poti sa bind-ui doar fragment-u'. Pentru orice altceva se poate folosi `onViewCreated`. Te ajuta sa-ti structurezi mai bine codu'

2021-05-25 14:32 UTC, pclRobert commented on app/src/main/java/com/example/taskkeeper/taskdetail/TaskDetailViewModelFactory.kt
> +class TaskDetailViewModelFactory( private var title : String) : ViewModelProvider.Factory {
Pattern-u' asta cu `ViewModelFactory` ii destul de invechit. `ViewModel`-urile se pot initializa mai usor cu ceea ce se numeste `by viewModels()`.

2021-05-25 14:32 UTC, pclRobert commented on app/src/main/java/com/example/taskkeeper/tasksviewer/TasksViewerFragment.kt
> +        tasksViewerViewModel.navigateToTaskDetail.observe(viewLifecycleOwner, Observer{
`Observer { ... }` ii redundant. Poti simplifica linia asta de cod: `.observe(viewLifecycleOwner) { ... }`

2021-05-26 14:04 UTC, SofranSebastian commented on app/src/main/java/com/example/taskkeeper/taskdetail/TaskDetailFragment.kt
> +        val binding : FragmentTaskDetailBinding = DataBindingUtil.inflate( inflater, R.layout.fragment_task_detail, container, false)
private lateinit var binding : FragmentTasksViewerBinding - am declarat-o asa global

2021-05-27 07:49 UTC, pclRobert requested changes

2021-05-27 07:49 UTC, pclRobert commented on app/src/main/java/com/example/taskkeeper/tasksviewer/TasksViewerFragment.kt
> +        val tasksViewerViewModel : TasksViewerViewModel by viewModels()
- [ ] `taskViewerViewModel` ar fi mai bine sa fie variabila globala

2021-05-27 07:49 UTC, pclRobert commented on app/src/main/java/com/example/taskkeeper/tasksviewer/TasksViewerFragment.kt
> +import android.text.Layout
Ai import-uri nefolosite.
Tip: _Ctrl + Alt + O_ iti sterge import-urile nefolosite.
Tip2: _Ctrl + Alt + L_ iti rearanjeaza codu' ca sa fie mai usor de citit.

2021-05-28 14:49 UTC, pclRobert approved these changes

2021-05-28 14:50 UTC, merged